import { z } from 'zod';
import { generateText, streamText, convertToModelMessages, type UIMessage } from 'ai';

import { getModel, type ProviderType } from '@/lib/ai/index';

import { createMemory, extractMemories, retrieveMemories } from '@/lib/ai/memory';

import { buildMemoryContext } from '@/lib/ai/context';

import { db } from '@/lib/db/config';
import { chats, messages } from '@/lib/db/schema';

import { eq } from 'drizzle-orm';

import { getCurrentUserId } from '@/lib/session';

export const maxDuration = 30;

export const runtime = 'nodejs';

const requestBodySchema = z.object({
  messages: z.array(z.custom<UIMessage>()),
  id: z.string().optional(),
  provider: z.string().optional().default('groq'),
  modelId: z.string().optional(),
});

function getMessageText(message: UIMessage): string {
  if (typeof (message as any).content === 'string') {
    return (message as any).content;
  }

  if (message.parts) {
    return message.parts
      .filter((part): part is Extract<typeof part, { type: 'text' }> => part.type === 'text')
      .map((part) => part.text)
      .join('');
  }

  return '';
}

/**
 * Generate a short, descriptive title for a chat.
 *
 * The title is generated from the user's first message and
 * the assistant's response so that it describes the actual
 * purpose/topic of the conversation rather than simply
 * copying the user's message.
 */
async function generateChatTitle(
  model: ReturnType<typeof getModel>,
  userMessage: string,
  assistantResponse: string,
): Promise<string> {
  try {
    const result = await generateText({
      model,

      system: `
You generate short titles for AI chat conversations.

Your task is to create a concise title that describes the main
topic or purpose of the conversation.

Rules:
- Use 3 to 7 words.
- Clearly describe the main topic.
- Do not simply copy the user's message.
- Do not answer the user's question.
- Do not use quotes.
- Do not use markdown.
- Do not include a period at the end.
- Do not start with words like "Chat", "Conversation", or "Discussion".
- Return ONLY the title.
`.trim(),

      prompt: `
User's first message:
${userMessage}

Assistant's response:
${assistantResponse}

Generate a concise and descriptive title for this conversation.
`.trim(),

      maxRetries: 2,
    });

    const title = result.text
      .replace(/^["'`]+|["'`]+$/g, '')
      .replace(/\s+/g, ' ')
      .replace(/[.!?]+$/g, '')
      .trim();

    if (!title) {
      return 'New Chat';
    }

    return title.slice(0, 100);
  } catch (error) {
    console.error('[Alpha AI] Failed to generate chat title:', error);

    return 'New Chat';
  }
}

export async function POST(req: Request) {
  try {
    /*
     * 1. Parse request
     */
    let body: unknown;

    try {
      body = await req.json();
    } catch {
      return Response.json(
        {
          error: 'Invalid JSON request body',
        },
        {
          status: 400,
        },
      );
    }

    /*
     * 2. Validate request
     */
    const parsed = requestBodySchema.safeParse(body);

    if (!parsed.success) {
      return Response.json(
        {
          error: 'Invalid request body',
          details: parsed.error.flatten(),
        },
        {
          status: 400,
        },
      );
    }

    const { messages: incomingMessages, id: chatId, provider, modelId } = parsed.data;

    /*
     * 3. Current user
     */
    const userId = await getCurrentUserId();

    /*
     * 4. Select model
     *
     * The same selected model is used for:
     * - AI response
     * - memory extraction
     * - chat title generation
     */
    const selectedModel = getModel(provider as ProviderType, modelId);

    /*
     * 5. Retrieve persistent memory
     */
    const userMemories = await retrieveMemories(userId);

    /*
     * 6. Build memory context
     */
    const memoryContext = buildMemoryContext(userMemories);

    /*
     * 7. System prompt
     */
    const systemPrompt = `
You are Alpha AI.

You are a helpful, knowledgeable and concise AI assistant.

Always provide accurate, clear and well-structured answers.

${memoryContext}
`.trim();

    /*
     * 8. Ensure chat exists
     *
     * New chats are initially created with "New Chat".
     * The actual title will be generated by the AI after
     * the first assistant response is complete.
     */
    let isNewChat = false;

    if (chatId) {
      const existingChat = await db.select().from(chats).where(eq(chats.id, chatId)).limit(1);

      if (existingChat.length === 0) {
        isNewChat = true;

        await db.insert(chats).values({
          id: chatId,
          userId,
          title: 'New Chat',
        });
      }
    }

    /*
     * 9. Get latest user message
     */
    const lastMessage = incomingMessages[incomingMessages.length - 1];

    const latestUserMessage = lastMessage?.role === 'user' ? getMessageText(lastMessage) : '';

    /*
     * 10. Persist user message
     */
    if (latestUserMessage && chatId && lastMessage?.role === 'user') {
      try {
        await db.insert(messages).values({
          chatId,
          role: 'user',
          content: latestUserMessage,
        });
      } catch (error) {
        console.error('[Alpha AI] Failed to save user message:', error);
      }
    }

    /*
     * 11. Convert messages for the model
     */
    const modelMessages = await convertToModelMessages(incomingMessages);

    /*
     * 12. Generate response
     */
    const result = streamText({
      model: selectedModel,

      system: systemPrompt,

      messages: modelMessages,

      maxRetries: 5,

      abortSignal: req.signal,

      /*
       * Save assistant response after generation.
       */
      onFinish: async ({ text }) => {
        /*
         * Save assistant message
         */
        if (chatId && text) {
          try {
            await db.insert(messages).values({
              chatId,
              role: 'assistant',
              content: text,
            });
          } catch (error) {
            console.error('[Alpha AI] Failed to save AI response:', error);
          }
        }

        /*
         * Generate AI chat title
         *
         * Only generate a title when this is a newly created
         * conversation. Existing conversations keep their
         * existing title.
         */
        if (isNewChat && chatId && latestUserMessage && text) {
          try {
            const title = await generateChatTitle(selectedModel, latestUserMessage, text);

            await db
              .update(chats)
              .set({
                title,
              })
              .where(eq(chats.id, chatId));

            console.log(`[Alpha AI] Generated chat title: "${title}"`);
          } catch (error) {
            console.error('[Alpha AI] Failed to save chat title:', error);
          }
        }

        /*
         * Extract and save persistent memories
         */
        if (latestUserMessage) {
          try {
            const extracted = await extractMemories(selectedModel, latestUserMessage);

            for (const memory of extracted.memories) {
              await createMemory({
                userId,
                content: memory.content,
                category: memory.category,
                source: memory.source,
              });
            }

            if (extracted.memories.length > 0) {
              console.log(`[Alpha AI] Saved ${extracted.memories.length} new memories.`);
            }
          } catch (error) {
            console.error('[Alpha AI] Failed to save memories:', error);
          }
        }
      },
    });

    /*
     * 13. Return stream
     */
    return result.toUIMessageStreamResponse();
  } catch (error) {
    console.error('[Alpha AI] API Error:', error);

    return new Response(
      JSON.stringify({
        error: 'Failed to generate AI response',
      }),
      {
        status: 500,
        headers: {
          'Content-Type': 'application/json',
        },
      },
    );
  }
}
